 
USE DataWarehouse;
--Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

SELECT TOP 10 * FROM gold.dim_products
SELECT TOP 10 * FROM gold.dim_customers
SELECT TOP 100 * FROM gold.fact_sales 


                        /*======================================
                               Dimension Exploration
                         =======================================*/
--Explore all countries oue customers come from..
SELECT DISTINCT country FROM gold.dim_customers

--Explore all category "The major Dicisons"
SELECT 
	DISTINCT category,subcategory,product_name
FROM gold.dim_products
ORDER BY 1,2,3

                        /*======================================
                                Date Exploration
                         =======================================*/

 --Identify the Latest Order Date
Select MAX(order_date) Last_order FROM gold.fact_sales

  --Identify the Earliest Order Date 
Select MIN(order_date) Frist_order FROM gold.fact_sales


                        /*===================================================
                           Measure Exploration - Highest level of aggregation
                         ===================================================*/

/*
    Find the total sales
    Find how many items are sold
    Find the avg selling price
    Find the total numbers of orders
    Find the total numbers of products
    Find the total numbers of customers
    Find the total numbers of customers that has placed an order 
*/

SELECT 'Total Sales' measure_name,  SUM(sales_amount) measure_value  FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total nr. Orders' , COUNT( DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total nr. Products' , COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total nr. Customers' , COUNT(customer_key) FROM gold.dim_customers



                        /*==================================
                            Magnitite Analysis
                         ===================================*/
--Compare the measure values by categories 
            -- It help us understand the importance of different categories


  -- What is the total revenue generated by each customers ? 
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(fs.sales_amount) Total_Sales
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales fs
    ON c.customer_key = fs.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY SUM(fs.sales_amount) DESC

  -- What is the distribution of sold items across countries ?

SELECT 
    c.country,
    SUM(fs.quantity) Total_sold_items
FROM gold.fact_sales fs
    LEFT JOIN gold.dim_customers c
ON fs.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Total_sold_items DESC


                        /*==================================
                           Ranking Analysis
                         ===================================*/

  -- Which 5 product generated the highest revenue?
SELECT
*
FROM ( 
        SELECT
            p.product_name,
            SUM(fs.sales_amount) total_sales,
            ROW_NUMBER() OVER(ORDER BY SUM(fs.sales_amount) DESC) rank_prodcuts
        FROM gold.fact_sales fs
        LEFT JOIN gold.dim_products p
            ON fs.product_key = p.product_key
        GROUP BY p.product_name
        )t
WHERE rank_prodcuts <= 5
  -- What are the 5 worst-performing prodcuts in terms of sales?

  
SELECT TOP 5
    p.product_name,
    SUM(fs.sales_amount) total_sales,
    ROW_NUMBER() OVER( ORDER BY SUM(fs.sales_amount) ) rank_prodcuts
FROM gold.fact_sales fs
    LEFT JOIN gold.dim_products p
ON fs.product_key = p.product_key
GROUP BY p.product_name


  -- SQL TASK:- Find Top-10 customers who have generated the highest revenue
                -- And customers with the fewest order placed

SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(fs.sales_amount) Total_Sales
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales fs
    ON c.customer_key = fs.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY Total_Sales DESC
--=====================================--
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(fs.order_number) Total_Orders
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales fs
    ON c.customer_key = fs.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY Total_Orders 
